/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package threefoursum;

import org.junit.Test;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertArrayEquals;

public class ThreeSumTest {
    @Test
    public void testThreeSum() {
        // Cases where there are no triplet
        int[] list_0_triplet = { 1, 2, 3 };

        assertNull(ThreeFourSum.threeSumCubic(list_0_triplet));
        assertNull(ThreeFourSum.threeSumQuadratic(list_0_triplet));
        assertNull(ThreeFourSum.threeSumHashMap(list_0_triplet));
        assertNull(ThreeFourSum.threeSumHashMapNoComparison(list_0_triplet));

        // Cases where there is one triplet
        int[] list_1_triplet_distinct = { 1, 2, -3 };
        int[] list_1_triplet_equal = { 2, -3, 2, 1, -3, 1}; // Case with equal integers

        assertNotNull(ThreeFourSum.threeSumCubic(list_1_triplet_distinct));
        assertNotNull(ThreeFourSum.threeSumQuadratic(list_1_triplet_distinct));
        assertNotNull(ThreeFourSum.threeSumHashMap(list_1_triplet_distinct));
        assertNotNull(ThreeFourSum.threeSumHashMapNoComparison(list_1_triplet_distinct));

        assertNotNull(ThreeFourSum.threeSumCubic(list_1_triplet_equal));
        assertNotNull(ThreeFourSum.threeSumQuadratic(list_1_triplet_equal));
        assertNotNull(ThreeFourSum.threeSumHashMap(list_1_triplet_equal));
        assertNotNull(ThreeFourSum.threeSumHashMapNoComparison(list_1_triplet_equal));

        // Case where there are multiple triplets
        // QUESTION: How relevant? I am indirectly testing triplets with 1 solution in our case
        int[] list_mult_input = { -1, 1, 2, 4, -3, -6 };
        int[] list_mult_input_equal = { 2, -1, 1, 2, 4, -3, -6 }; // Case with equal integers
        int[] list_mult_expected = { -1, 4, -3 };
        int[] list_mult_expected_sorted = { -6, 2, 4 }; // Exception for quadratic: sorted results

        assertNotNull(ThreeFourSum.threeSumCubic(list_mult_input));
        assertArrayEquals(list_mult_expected, ThreeFourSum.threeSumCubic(list_mult_expected));
        assertNotNull(ThreeFourSum.threeSumQuadratic(list_mult_input));
        assertArrayEquals(list_mult_expected_sorted, ThreeFourSum.threeSumQuadratic(list_mult_expected_sorted));
        assertNotNull(ThreeFourSum.threeSumHashMap(list_mult_input));
        assertArrayEquals(list_mult_expected, ThreeFourSum.threeSumHashMap(list_mult_expected));
        assertNotNull(ThreeFourSum.threeSumHashMapNoComparison(list_mult_input));
        assertArrayEquals(list_mult_expected, ThreeFourSum.threeSumHashMapNoComparison(list_mult_expected));

        assertNotNull(ThreeFourSum.threeSumCubic(list_mult_input_equal));
        assertArrayEquals(list_mult_expected, ThreeFourSum.threeSumCubic(list_mult_expected));
        assertNotNull(ThreeFourSum.threeSumQuadratic(list_mult_input_equal));
        assertArrayEquals(list_mult_expected_sorted, ThreeFourSum.threeSumQuadratic(list_mult_expected_sorted));
        assertNotNull(ThreeFourSum.threeSumHashMap(list_mult_input_equal));
        assertArrayEquals(list_mult_expected, ThreeFourSum.threeSumHashMap(list_mult_expected));
        assertNotNull(ThreeFourSum.threeSumHashMapNoComparison(list_mult_input_equal));
        assertArrayEquals(list_mult_expected, ThreeFourSum.threeSumHashMapNoComparison(list_mult_expected));

        // Cases where there are fewer than 3 distinct integers (1 or 2) in the list
        int[] list_2_el_false = { 1, -1 }; // Case with 2 elements summing up to 0

        assertNull(ThreeFourSum.threeSumCubic(list_2_el_false));
        assertNull(ThreeFourSum.threeSumQuadratic(list_2_el_false));
        assertNull(ThreeFourSum.threeSumHashMap(list_2_el_false));
        assertNull(ThreeFourSum.threeSumHashMapNoComparison(list_2_el_false));

        int[] list_2_el_true = { 1, 2 }; // Case with 2 elements not summing up to 0

        assertNull(ThreeFourSum.threeSumCubic(list_2_el_true));
        assertNull(ThreeFourSum.threeSumQuadratic(list_2_el_true));
        assertNull(ThreeFourSum.threeSumHashMap(list_2_el_true));
        assertNull(ThreeFourSum.threeSumHashMapNoComparison(list_2_el_true));

        int[] list_1_el_true = { 0 }; // Case with 1 element summing up to 0


        assertNull(ThreeFourSum.threeSumCubic(list_1_el_true));
        assertNull(ThreeFourSum.threeSumQuadratic(list_1_el_true));
        assertNull(ThreeFourSum.threeSumHashMap(list_1_el_true));
        assertNull(ThreeFourSum.threeSumHashMapNoComparison(list_1_el_true));

        int[] list_1_el_false = { 1 }; // Case with 1 element not summing up to 0

        assertNull(ThreeFourSum.threeSumCubic(list_1_el_false));
        assertNull(ThreeFourSum.threeSumQuadratic(list_1_el_false));
        assertNull(ThreeFourSum.threeSumHashMap(list_1_el_false));
        assertNull(ThreeFourSum.threeSumHashMapNoComparison(list_1_el_false));

        // Case where there is an empty list
        int[] list_empty = {};

        assertNull(ThreeFourSum.threeSumCubic(list_empty));
        assertNull(ThreeFourSum.threeSumQuadratic(list_empty));
        assertNull(ThreeFourSum.threeSumHashMap(list_empty));
        assertNull(ThreeFourSum.threeSumHashMapNoComparison(list_empty));

        // Cases where there are several equal integers, also less than 3 elements
        int[] list_equal_true = { 0, 0, 0 }; // Case with 3 equal integers summing up to 0

        assertNotNull(ThreeFourSum.threeSumCubic(list_equal_true));
        assertNotNull(ThreeFourSum.threeSumQuadratic(list_equal_true));
        assertNotNull(ThreeFourSum.threeSumHashMap(list_equal_true));
        assertNotNull(ThreeFourSum.threeSumHashMapNoComparison(list_equal_true));

        int[] list_equal_false = { 1, 1, 1 }; // Case with 3 equal integers not summing up to 0

        assertNull(ThreeFourSum.threeSumCubic(list_equal_false));
        assertNull(ThreeFourSum.threeSumQuadratic(list_equal_false));
        assertNull(ThreeFourSum.threeSumHashMap(list_equal_false));
        assertNull(ThreeFourSum.threeSumHashMapNoComparison(list_equal_false));

        int[] list_equal_2_el_false = { 1, 1 }; // Case with 2 equal integers not summing up to 0

        assertNull(ThreeFourSum.threeSumCubic(list_equal_2_el_false));
        assertNull(ThreeFourSum.threeSumQuadratic(list_equal_2_el_false));
        assertNull(ThreeFourSum.threeSumHashMap(list_equal_2_el_false));
        assertNull(ThreeFourSum.threeSumHashMapNoComparison(list_equal_2_el_false));

        int[] list_equal_2_el_true = { 0, 0 }; // Case with 2 equal integers summing up to 0

        assertNull(ThreeFourSum.threeSumCubic(list_equal_2_el_true));
        assertNull(ThreeFourSum.threeSumQuadratic(list_equal_2_el_true));
        assertNull(ThreeFourSum.threeSumHashMap(list_equal_2_el_true));

        // Case with only negative integers
        int [] list_negatives = { -1, -2, -3, -4, -5 };

        assertNull(ThreeFourSum.threeSumCubic(list_negatives));
        assertNull(ThreeFourSum.threeSumQuadratic(list_negatives));
        assertNull(ThreeFourSum.threeSumHashMap(list_negatives));
        assertNull(ThreeFourSum.threeSumHashMapNoComparison(list_negatives));

        /* Cases where HashMap provides a correct solution and the version without comparison does not */
        int[] list_hash_1 = { 0, 0 };
        int[] list_hash_2 = { 3, -6, 1 };

        assertNull(ThreeFourSum.threeSumHashMap(list_hash_1));
        assertNotNull(ThreeFourSum.threeSumHashMapNoComparison(list_hash_1));
        assertNull(ThreeFourSum.threeSumHashMap(list_hash_2));
        assertNotNull(ThreeFourSum.threeSumHashMapNoComparison(list_hash_2));
    }
}